### ISSUE TITLE
Add editText on dialog

### ISSUE THREAD

**Issue by dca-ps** [BROUDING/SimpleDialog#1]
Hi!
Great job on the dialog! It's great and easy to use!
Is it possible to add an editText on the dialog? I've been wanting to put it to make an introduction on my app. Is it possible?

**Comment by BROUDING** [comment]
Hello ! @dca-ps 
Thanks :)
If you try to draw or specify more details about adding EditText in where, that would be helpful !

I'm working on CustomView to add, Is that gonna be enough?

**Comment by BROUDING** [comment]
@dca-ps 
I updated version 0.3.0, and you can make your own Custom Simple Dialog!
Check out in [Wiki](https://github.com/BROUDING/SimpleDialog/wiki/How-to-use#custom-dialog) :)
