### ISSUE TITLE
Build failed on target 26

### ISSUE THREAD

**Issue by princeHago** [BROUDING/SimpleDialog#3]
Hi, i use your component in my apps.

I love it, but after upgrade to compileSdkVersion 26, i get this error:

> Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar]
C:\Users\agostino.delcore\.gradle\caches\transforms-1\files-1.1\appcompat-v7-26.1.0.aar\6985a0942fe8dace54cb23ff49003e14\res\values\values.xml
Error:(1685, 5) error: style attribute '@android:attr/windowBackground' not found.
Error:(1685, 5) error: style attribute '@android:attr/colorAccent' not found.
Error:(1685, 5) error: style attribute '@android:attr/windowEnterAnimation' not found.
Error:(1685, 5) error: style attribute '@android:attr/windowExitAnimation' not found.
C:\Users\agostino.delcore\Google Drive\AndroidstudioProjects\WinClick\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Error:(2553) style attribute '@android:attr/windowBackground' not found.
Error:(2554) style attribute '@android:attr/colorAccent' not found.
Error:(2555) style attribute '@android:attr/windowEnterAnimation' not found.
Error:(2556) style attribute '@android:attr/windowExitAnimation' not found.
Error:failed linking references.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt
Information:BUILD FAILED in 10s
Information:13 errors
Information:0 warnings
Information:See complete output in console

How i can resolve?

Thanks in advance

**Comment by BROUDING** [comment]
@princeHago 
Hello Hago, thanks for using this component.
Can you explain to me more details of this incident? 
Or it happened JUST after you changed `compileSdkVersion` ?
Can you try Cleaning the project and Rebuilding it?

If that doesn't work, 
1) remove `compile 'com.brouding:android-simple-dialog:0.2.5.3'`
2) sync your gradle
3) and add compile `'com.brouding:android-simple-dialog:0.2.5.3'`
4) and sync your gradle again


My project is also using this component, and using `compileSdkVersion` as 27, without any issue.


Thanks !

**Comment by princeHago** [comment]
Hi,

thanks in advance for your reply.

I following this step:

remove compile 'com.brouding:android-simple-dialog:0.2.5.3'
sync your gradle --> OK
and add compile 'com.brouding:android-simple-dialog:0.2.5.3'
and sync your gradle again --> KO

> Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar]
C:\Users\agostino.delcore\.gradle\caches\transforms-1\files-1.1\appcompat-v7-26.1.0.aar\6985a0942fe8dace54cb23ff49003e14\res\values\values.xml
Error:(1685, 5) error: style attribute '@android:attr/windowBackground' not found.
Error:(1685, 5) error: style attribute '@android:attr/colorAccent' not found.
Error:(1685, 5) error: style attribute '@android:attr/windowEnterAnimation' not found.
Error:(1685, 5) error: style attribute '@android:attr/windowExitAnimation' not found.
C:\Users\agostino.delcore\Google Drive\AndroidstudioProjects\WinClick\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Error:(2573) style attribute '@android:attr/windowBackground' not found.
Error:(2574) style attribute '@android:attr/colorAccent' not found.
Error:(2575) style attribute '@android:attr/windowEnterAnimation' not found.
Error:(2576) style attribute '@android:attr/windowExitAnimation' not found.
Error:failed linking references.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt
Information:BUILD FAILED in 11s
Information:13 errors
Information:0 warnings
Information:See complete output in console

This is my app grandle:
`buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
        maven { url 'https://jitpack.io' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
    maven { url 'https://jitpack.io' }
    maven { url "https://maven.google.com" }
    maven { url 'https://houndify.com/maven/' }
}


android {
    compileSdkVersion 26
    useLibrary 'org.apache.http.legacy'
    defaultConfig {
        applicationId "XXXXXXXXXXXXXXXXXXXX"
        minSdkVersion 17
        targetSdkVersion 26
        versionCode 8
        versionName "0.0.8"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/license.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/NOTICE'
    }
    aaptOptions {
        noCompress "waw"
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile group: 'org.apache.httpcomponents', name: 'httpclient-android', version: '4.3.5.1'
    compile('org.apache.httpcomponents:httpmime:4.3') {
        exclude module: "httpclient"
    }

    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true;
    }

    compile('cn.trinea.android.view.autoscrollviewpager:android-auto-scroll-view-pager:1.1.2') {
        exclude module: 'support-v4'
    }

    // ANDROID
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support:design:26.+'
    compile 'com.android.support:support-vector-drawable:26.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:support-v4:26.1.0'

    // GOOGLE
    compile 'com.firebase:firebase-jobdispatcher-with-gcm-dep:0.6.0'
    compile 'com.google.firebase:firebase-messaging:11.6.0'
    compile 'com.google.firebase:firebase-config:11.6.0'
    compile 'com.google.firebase:firebase-crash:11.6.0'
    compile 'com.google.firebase:firebase-core:11.6.0'
    compile 'com.google.code.gson:gson:2.8.2'
    compile('com.crashlytics.sdk.android:crashlytics:2.7.1@aar') {
        transitive = true
    }

    // 3RD PARTS- UI
    compile 'com.github.justzak:dilatingdotsprogressbar:1.0.1'
    compile 'me.drakeet.materialdialog:library:1.3.1'
    compile 'com.github.lzyzsd:circleprogress:1.2.1'
    compile 'com.dsdmsa.text:text_decor_V01:0.0.5'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.brouding:android-simple-dialog:0.3.0'

    // 3RD PARTS - UTILS - NETWORK
    compile 'com.github.ravindu1024:velocity:1.0.4'

    // 3RD PARTS - UTILS - FILES
    compile 'com.github.pavlospt:rxfile:1.5'

    testCompile 'junit:junit:4.12'
}

apply plugin: 'com.google.gms.google-services'`
And this my project grandle:
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
        classpath 'com.google.gms:google-services:3.1.1'
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url 'https://maven.google.com' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by princeHago** [comment]
news?

**Comment by BROUDING** [comment]
Sorry for late reply, I've been stucked on some issue.
Can you try new version (0.3.1) and let me know if it works for you?

`compile 'com.brouding:android-simple-dialog:0.3.1'`

**Comment by princeHago** [comment]
Hi, be quiet.

I update the compile version to 0.3.1 and now work perfectly.

Thanks for your support. Take care.
